# Generated by Django 5.2.8 on 2026-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('Startup', 'Startup'), ('Small Business', 'Small Business'), ('Enterprise', 'Enterprise'), ('Personal Brand', 'Personal Brand'), ('Portfolio Site', 'Portfolio Site'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Description of the business')),
                ('requirements', models.TextField(help_text='Website requirements and preferences')),
                ('package', models.CharField(choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='Starter', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Request',
                'verbose_name_plural': 'Project Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
