# Generated by Django 5.2.7 on 2025-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clientprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
    ]
